name: Run Stack Guardian Functions
on:
  workflow_dispatch:
  push:
  # pull_request_target: 
  
env:
  # sg_token: ${{ secrets.SG_API_TOKEN }}
  app_name: "GH-Deployed-Application"
  organization: "wicked-hop"
  cloud_platform: "aws"

jobs:
  trigger-workflow:
    name: Run StackGuardian Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Execute API Call
        run : |
          pwd
          echo "Application to deploy: ${{ env.app_name }}"
          curl --location 'https://api.app.stackguardian.io/api/v1/orgs/${{ env.organization }}/wfgrps/listall/' --header 'Authorization: apikey ${{ secrets.SG_API_TOKEN }}' --header 'Accept: application/json' 
        
